import { suite } from "node:test";
import { createSimpleTestFileSkip, testSimpleTestFile } from "./testing.js";
import { getSimpleTestFiles } from "@bufbuild/cel-spec/testdata/simple.js";
import { getTestRegistry } from "@bufbuild/cel-spec/testdata/registry.js";

const files = getSimpleTestFiles();

const shouldSkip = createSimpleTestFileSkip(files, [
  ["bindings_ext"],
  ["block_ext"],
  ["conversions", "bool", "string_1"],
  ["conversions", "bool", "string_t"],
  ["conversions", "bool", "string_true_uppercase"],
  ["conversions", "bool", "string_true_pascalcase"],
  ["conversions", "bool", "string_true_badcase"],
  ["conversions", "bool", "string_false_badcase"],
  ["dynamic", "int32", "literal"],
  ["dynamic", "int32", "literal_zero"],
  ["dynamic", "int32", "var"],
  ["dynamic", "int32", "field_assign_proto2"],
  ["dynamic", "int32", "field_assign_proto2_zero"],
  ["dynamic", "int32", "field_assign_proto2_max"],
  ["dynamic", "int32", "field_assign_proto2_min"],
  ["dynamic", "int32", "field_assign_proto2_range"],
  ["dynamic", "int32", "field_read_proto2"],
  ["dynamic", "int32", "field_read_proto2_zero"],
  ["dynamic", "int32", "field_assign_proto3"],
  ["dynamic", "int32", "field_assign_proto3_zero"],
  ["dynamic", "int32", "field_assign_proto3_max"],
  ["dynamic", "int32", "field_assign_proto3_min"],
  ["dynamic", "int32", "field_assign_proto3_range"],
  ["dynamic", "int32", "field_read_proto3"],
  ["dynamic", "int32", "field_read_proto3_zero"],
  ["dynamic", "int64", "literal"],
  ["dynamic", "int64", "literal_zero"],
  ["dynamic", "int64", "var"],
  ["dynamic", "int64", "field_assign_proto2"],
  ["dynamic", "int64", "field_assign_proto2_zero"],
  ["dynamic", "int64", "field_assign_proto3"],
  ["dynamic", "int64", "field_assign_proto3_zero"],
  ["dynamic", "uint32", "literal"],
  ["dynamic", "uint32", "literal_zero"],
  ["dynamic", "uint32", "var"],
  ["dynamic", "uint32", "field_assign_proto2"],
  ["dynamic", "uint32", "field_assign_proto2_zero"],
  ["dynamic", "uint32", "field_assign_proto2_max"],
  ["dynamic", "uint32", "field_assign_proto2_range"],
  ["dynamic", "uint32", "field_assign_proto3"],
  ["dynamic", "uint32", "field_assign_proto3_zero"],
  ["dynamic", "uint32", "field_assign_proto3_max"],
  ["dynamic", "uint32", "field_assign_proto3_range"],
  ["dynamic", "uint32", "field_read_proto2"],
  ["dynamic", "uint32", "field_read_proto2_zero"],
  ["dynamic", "uint64", "literal"],
  ["dynamic", "uint64", "literal_zero"],
  ["dynamic", "uint64", "var"],
  ["dynamic", "uint64", "field_assign_proto2"],
  ["dynamic", "uint64", "field_assign_proto2_zero"],
  ["dynamic", "uint64", "field_assign_proto3"],
  ["dynamic", "uint64", "field_assign_proto3_zero"],
  ["dynamic", "uint64", "field_read_proto2"],
  ["dynamic", "uint64", "field_read_proto2_zero"],
  ["dynamic", "float", "literal"],
  ["dynamic", "float", "literal_not_double"],
  ["dynamic", "float", "literal_zero"],
  ["dynamic", "float", "var"],
  ["dynamic", "float", "field_assign_proto2"],
  ["dynamic", "float", "field_assign_proto2_zero"],
  ["dynamic", "float", "field_assign_proto2_subnorm"],
  ["dynamic", "float", "field_assign_proto2_round_to_zero"],
  ["dynamic", "float", "field_assign_proto2_range"],
  ["dynamic", "float", "field_read_proto2"],
  ["dynamic", "float", "field_read_proto2_zero"],
  ["dynamic", "float", "field_assign_proto3"],
  ["dynamic", "float", "field_assign_proto3_zero"],
  ["dynamic", "float", "field_assign_proto3_round_to_zero"],
  ["dynamic", "float", "field_assign_proto3_range"],
  ["dynamic", "float", "field_read_proto3"],
  ["dynamic", "float", "field_read_proto3_zero"],
  ["dynamic", "double", "literal"],
  ["dynamic", "double", "literal_zero"],
  ["dynamic", "double", "var"],
  ["dynamic", "double", "field_assign_proto2"],
  ["dynamic", "double", "field_assign_proto2_zero"],
  ["dynamic", "double", "field_assign_proto2_range"],
  ["dynamic", "double", "field_read_proto2"],
  ["dynamic", "double", "field_read_proto2_zero"],
  ["dynamic", "double", "field_assign_proto3"],
  ["dynamic", "double", "field_assign_proto3_zero"],
  ["dynamic", "double", "field_read_proto3"],
  ["dynamic", "double", "field_read_proto3_zero"],
  ["dynamic", "double", "field_assign_proto3_range"],
  ["dynamic", "bool", "literal"],
  ["dynamic", "bool", "literal_empty"],
  ["dynamic", "bool", "var"],
  ["dynamic", "bool", "field_assign_proto2"],
  ["dynamic", "bool", "field_assign_proto2_false"],
  ["dynamic", "bool", "field_assign_proto3"],
  ["dynamic", "bool", "field_assign_proto3_false"],
  ["dynamic", "string", "literal"],
  ["dynamic", "string", "literal_empty"],
  ["dynamic", "string", "literal_unicode"],
  ["dynamic", "string", "var"],
  ["dynamic", "string", "field_assign_proto2"],
  ["dynamic", "string", "field_assign_proto2_empty"],
  ["dynamic", "string", "field_assign_proto3"],
  ["dynamic", "string", "field_assign_proto3_empty"],
  ["dynamic", "bytes", "literal"],
  ["dynamic", "bytes", "literal_empty"],
  ["dynamic", "bytes", "literal_unicode"],
  ["dynamic", "bytes", "var"],
  ["dynamic", "bytes", "field_assign_proto2"],
  ["dynamic", "bytes", "field_assign_proto2_empty"],
  ["dynamic", "bytes", "field_assign_proto3"],
  ["dynamic", "bytes", "field_assign_proto3_empty"],
  ["dynamic", "list", "literal"],
  ["dynamic", "list", "literal_no_field_access"],
  ["dynamic", "list", "literal_empty"],
  ["dynamic", "list", "var"],
  ["dynamic", "list", "field_assign_proto2"],
  ["dynamic", "list", "field_assign_proto2_empty"],
  ["dynamic", "list", "field_read_proto2"],
  ["dynamic", "list", "field_read_proto2_empty"],
  ["dynamic", "list", "field_read_proto2_unset"],
  ["dynamic", "list", "field_assign_proto3"],
  ["dynamic", "list", "field_assign_proto3_empty"],
  ["dynamic", "list", "field_read_proto3"],
  ["dynamic", "list", "field_read_proto3_empty"],
  ["dynamic", "list", "field_read_proto3_unset"],
  ["dynamic", "struct", "literal"],
  ["dynamic", "struct", "literal_no_field_access"],
  ["dynamic", "struct", "literal_empty"],
  ["dynamic", "struct", "var"],
  ["dynamic", "struct", "field_assign_proto2"],
  ["dynamic", "struct", "field_assign_proto2_empty"],
  ["dynamic", "struct", "field_read_proto2"],
  ["dynamic", "struct", "field_read_proto2_empty"],
  ["dynamic", "struct", "field_read_proto2_unset"],
  ["dynamic", "struct", "field_assign_proto3"],
  ["dynamic", "struct", "field_assign_proto3_empty"],
  ["dynamic", "struct", "field_read_proto3"],
  ["dynamic", "struct", "field_read_proto3_empty"],
  ["dynamic", "struct", "field_read_proto3_unset"],
  ["dynamic", "value_null", "literal"],
  ["dynamic", "value_null", "var"],
  ["dynamic", "value_null", "field_assign_proto2"],
  ["dynamic", "value_null", "field_read_proto2"],
  ["dynamic", "value_null", "field_assign_proto3"],
  ["dynamic", "value_null", "field_read_proto3"],
  ["dynamic", "value_number", "literal"],
  ["dynamic", "value_number", "literal_zero"],
  ["dynamic", "value_number", "var"],
  ["dynamic", "value_number", "field_assign_proto2"],
  ["dynamic", "value_number", "field_assign_proto2_zero"],
  ["dynamic", "value_number", "field_read_proto2"],
  ["dynamic", "value_number", "field_read_proto2_zero"],
  ["dynamic", "value_number", "field_assign_proto3"],
  ["dynamic", "value_number", "field_assign_proto3_zero"],
  ["dynamic", "value_number", "field_read_proto3"],
  ["dynamic", "value_number", "field_read_proto3_zero"],
  ["dynamic", "value_string", "literal"],
  ["dynamic", "value_string", "literal_empty"],
  ["dynamic", "value_string", "var"],
  ["dynamic", "value_string", "field_assign_proto2"],
  ["dynamic", "value_string", "field_assign_proto2_empty"],
  ["dynamic", "value_string", "field_read_proto2"],
  ["dynamic", "value_string", "field_read_proto2_zero"],
  ["dynamic", "value_string", "field_assign_proto3"],
  ["dynamic", "value_string", "field_assign_proto3_empty"],
  ["dynamic", "value_string", "field_read_proto3"],
  ["dynamic", "value_string", "field_read_proto3_zero"],
  ["dynamic", "value_bool", "literal"],
  ["dynamic", "value_bool", "literal_false"],
  ["dynamic", "value_bool", "var"],
  ["dynamic", "value_bool", "field_read_proto2_false"],
  ["dynamic", "value_bool", "field_read_proto2"],
  ["dynamic", "value_bool", "field_read_proto3"],
  ["dynamic", "value_bool", "field_read_proto3_false"],
  ["dynamic", "value_bool", "field_assign_proto2"],
  ["dynamic", "value_bool", "field_assign_proto2_false"],
  ["dynamic", "value_bool", "field_assign_proto3"],
  ["dynamic", "value_bool", "field_assign_proto3_false"],
  ["dynamic", "value_struct", "literal"],
  ["dynamic", "value_struct", "literal_no_field_access"],
  ["dynamic", "value_struct", "literal_empty"],
  ["dynamic", "value_struct", "var"],
  ["dynamic", "value_struct", "field_assign_proto2"],
  ["dynamic", "value_struct", "field_assign_proto2_empty"],
  ["dynamic", "value_struct", "field_read_proto2"],
  ["dynamic", "value_struct", "field_read_proto2_empty"],
  ["dynamic", "value_struct", "field_assign_proto3"],
  ["dynamic", "value_struct", "field_assign_proto3_empty"],
  ["dynamic", "value_struct", "field_read_proto3"],
  ["dynamic", "value_struct", "field_read_proto3_empty"],
  ["dynamic", "value_list", "literal"],
  ["dynamic", "value_list", "literal_no_field_access"],
  ["dynamic", "value_list", "literal_empty"],
  ["dynamic", "value_list", "var"],
  ["dynamic", "value_list", "field_assign_proto2"],
  ["dynamic", "value_list", "field_assign_proto2_empty"],
  ["dynamic", "value_list", "field_read_proto2"],
  ["dynamic", "value_list", "field_read_proto2_empty"],
  ["dynamic", "value_list", "field_assign_proto3"],
  ["dynamic", "value_list", "field_assign_proto3_empty"],
  ["dynamic", "value_list", "field_read_proto3"],
  ["dynamic", "value_list", "field_read_proto3_empty"],
  ["dynamic", "any", "literal"],
  ["dynamic", "any", "literal_no_field_access"],
  ["dynamic", "any", "literal_empty"],
  ["dynamic", "any", "var"],
  ["dynamic", "any", "field_assign_proto2"],
  ["dynamic", "any", "field_read_proto2"],
  ["dynamic", "any", "field_assign_proto3"],
  ["dynamic", "any", "field_read_proto3"],
  ["dynamic", "complex", "any_list_map"],
  ["encoders_ext", "encode", "hello"],
  ["encoders_ext", "decode", "hello"],
  ["encoders_ext", "decode", "hello_without_padding"],
  ["encoders_ext", "round_trip", "hello"],
  ["enums", "legacy_proto2", "literal_global"],
  ["enums", "legacy_proto2", "literal_nested"],
  ["enums", "legacy_proto2", "literal_zero"],
  ["enums", "legacy_proto2", "comparision"],
  ["enums", "legacy_proto2", "arithmetic"],
  ["enums", "legacy_proto2", "type_global"],
  ["enums", "legacy_proto2", "type_nested"],
  ["enums", "legacy_proto2", "select_default"],
  ["enums", "legacy_proto2", "field_type"],
  ["enums", "legacy_proto2", "assign_standalone_name"],
  ["enums", "legacy_proto2", "assign_standalone_int"],
  ["enums", "legacy_proto2", "assign_standalone_int_too_big"],
  ["enums", "legacy_proto2", "assign_standalone_int_too_neg"],
  ["enums", "legacy_proto3", "literal_global"],
  ["enums", "legacy_proto3", "literal_nested"],
  ["enums", "legacy_proto3", "literal_zero"],
  ["enums", "legacy_proto3", "comparision"],
  ["enums", "legacy_proto3", "arithmetic"],
  ["enums", "legacy_proto3", "type_global"],
  ["enums", "legacy_proto3", "type_nested"],
  ["enums", "legacy_proto3", "select"],
  ["enums", "legacy_proto3", "select_big"],
  ["enums", "legacy_proto3", "select_neg"],
  ["enums", "legacy_proto3", "field_type"],
  ["enums", "legacy_proto3", "assign_standalone_name"],
  ["enums", "legacy_proto3", "assign_standalone_int"],
  ["enums", "legacy_proto3", "assign_standalone_int_big"],
  ["enums", "legacy_proto3", "assign_standalone_int_neg"],
  ["enums", "legacy_proto3", "assign_standalone_int_too_big"],
  ["enums", "legacy_proto3", "assign_standalone_int_too_neg"],
  ["enums", "strong_proto2", "literal_global"],
  ["enums", "strong_proto2", "literal_nested"],
  ["enums", "strong_proto2", "literal_zero"],
  ["enums", "strong_proto2", "comparision_true"],
  ["enums", "strong_proto2", "comparision_false"],
  ["enums", "strong_proto2", "type_global"],
  ["enums", "strong_proto2", "type_nested"],
  ["enums", "strong_proto2", "select_default"],
  ["enums", "strong_proto2", "field_type"],
  ["enums", "strong_proto2", "assign_standalone_name"],
  ["enums", "strong_proto2", "assign_standalone_int"],
  ["enums", "strong_proto2", "convert_symbol_to_int"],
  ["enums", "strong_proto2", "convert_unnamed_to_int"],
  ["enums", "strong_proto2", "convert_int_inrange"],
  ["enums", "strong_proto2", "convert_int_big"],
  ["enums", "strong_proto2", "convert_int_neg"],
  ["enums", "strong_proto2", "convert_string"],
  ["enums", "strong_proto3", "literal_global"],
  ["enums", "strong_proto3", "literal_nested"],
  ["enums", "strong_proto3", "literal_zero"],
  ["enums", "strong_proto3", "comparision_true"],
  ["enums", "strong_proto3", "comparision_false"],
  ["enums", "strong_proto3", "type_global"],
  ["enums", "strong_proto3", "type_nested"],
  ["enums", "strong_proto3", "select_default"],
  ["enums", "strong_proto3", "field_type"],
  ["enums", "strong_proto3", "assign_standalone_name"],
  ["enums", "strong_proto3", "assign_standalone_int"],
  ["enums", "strong_proto3", "convert_symbol_to_int"],
  ["enums", "strong_proto3", "convert_unnamed_to_int"],
  ["enums", "strong_proto3", "convert_int_inrange"],
  ["enums", "strong_proto3", "convert_int_big"],
  ["enums", "strong_proto3", "convert_int_neg"],
  ["enums", "strong_proto3", "convert_string"],
  ["enums", "strong_proto3", "select"],
  ["enums", "strong_proto3", "select_big"],
  ["enums", "strong_proto3", "select_neg"],
  ["enums", "strong_proto3", "assign_standalone_int_big"],
  ["enums", "strong_proto3", "assign_standalone_int_neg"],
  ["enums", "strong_proto3", "convert_unnamed_to_int_select"],
  [
    "fields",
    "qualified_identifier_resolution",
    "map_value_repeat_key_heterogeneous",
  ],
  ["math_ext", "greatest_int_result"],
  ["math_ext", "greatest_double_result"],
  ["math_ext", "greatest_uint_result"],
  ["math_ext", "least_int_result"],
  ["math_ext", "least_double_result"],
  ["math_ext", "least_uint_result"],
  ["math_ext", "ceil"],
  ["math_ext", "floor"],
  ["math_ext", "round"],
  ["math_ext", "trunc"],
  ["math_ext", "abs"],
  ["math_ext", "sign"],
  ["math_ext", "isNaN"],
  ["math_ext", "isInf"],
  ["math_ext", "isFinite"],
  ["math_ext", "bit_and"],
  ["math_ext", "bit_or"],
  ["math_ext", "bit_xor"],
  ["math_ext", "bit_not"],
  ["math_ext", "bit_shift_left"],
  ["math_ext", "bit_shift_right"],
  ["optionals", "optionals"],
  ["proto2", "literal_singular", "int64_nocontainer"],
  ["proto2", "literal_singular", "int32"],
  ["proto2", "literal_singular", "int64"],
  ["proto2", "literal_singular", "uint32"],
  ["proto2", "literal_singular", "uint64"],
  ["proto2", "literal_singular", "sint32"],
  ["proto2", "literal_singular", "sint64"],
  ["proto2", "literal_singular", "fixed32"],
  ["proto2", "literal_singular", "fixed64"],
  ["proto2", "literal_singular", "sfixed32"],
  ["proto2", "literal_singular", "sfixed64"],
  ["proto2", "literal_singular", "float"],
  ["proto2", "literal_singular", "double"],
  ["proto2", "literal_singular", "bool"],
  ["proto2", "literal_singular", "string"],
  ["proto2", "literal_singular", "bytes"],
  ["proto2", "literal_wellknown"],
  ["proto2", "singular_bind"],
  ["proto2", "empty_field", "scalar_with_default"],
  ["proto2", "empty_field", "nested_message"],
  ["proto2", "empty_field", "map"],
  ["proto2", "has", "repeated_none_implicit"],
  ["proto2", "has", "repeated_none_explicit"],
  ["proto2", "has", "map_none_implicit"],
  ["proto2", "has", "map_none_explicit"],
  ["proto2", "has", "required"],
  ["proto2", "has", "optional_unset_no_default"],
  ["proto2", "has", "optional_unset_with_default"],
  ["proto2", "has", "optional_message_unset"],
  ["proto2", "has", "optional_enum_set"],
  ["proto2", "has", "optional_enum_set_zero"],
  ["proto2", "has", "oneof_unset"],
  ["proto2", "has", "oneof_other_set"],
  ["proto2", "has", "oneof_set_default"],
  ["proto2", "set_null"],
  ["proto2_ext"],
  ["proto3", "literal_singular"],
  ["proto3", "literal_wellknown"],
  ["proto3", "singular_bind"],
  ["proto3", "empty_field", "nested_message"],
  ["proto3", "empty_field", "map"],
  ["proto3", "has", "repeated_none_implicit"],
  ["proto3", "has", "repeated_none_explicit"],
  ["proto3", "has", "map_none_implicit"],
  ["proto3", "has", "map_none_explicit"],
  ["proto3", "has", "single_unset"],
  ["proto3", "has", "single_set_to_default"],
  ["proto3", "has", "single_message_unset"],
  ["proto3", "has", "single_enum_unset"],
  ["proto3", "has", "single_enum_set"],
  ["proto3", "has", "single_enum_set_zero"],
  ["proto3", "has", "oneof_unset"],
  ["proto3", "has", "oneof_other_set"],
  ["proto3", "has", "oneof_set_default"],
  ["proto3", "set_null"],
  ["string_ext", "format", "scientific notation formatting clause"],
  ["string_ext", "format", "default precision for scientific notation"],
  ["string_ext", "format", "unicode output for scientific notation"],
  ["string_ext", "format", "map support for string"],
  ["string_ext", "format", "dyntype support for scientific notation"],
  [
    "string_ext",
    "format",
    "scientific notation formatting clause in a string variable",
  ],
  ["timestamps", "timestamp_selectors", "getMilliseconds"],
  ["wrappers", "bool"],
  ["wrappers", "int32"],
  ["wrappers", "int64"],
  ["wrappers", "uint32"],
  ["wrappers", "uint64"],
  ["wrappers", "float"],
  ["wrappers", "double"],
  ["wrappers", "bytes"],
  ["wrappers", "string"],
  ["wrappers", "list_value"],
  ["wrappers", "struct"],
  ["wrappers", "field_mask"],
  ["wrappers", "duration"],
  ["wrappers", "timestamp"],
  ["wrappers", "empty"],
]);

void suite("Conformance Tests", () => {
  const typeRegistry = getTestRegistry();
  for (const file of files) {
    void testSimpleTestFile(file, typeRegistry, shouldSkip);
  }
});
